/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ldw_testjnicmake_JniUtils */

#ifndef _Included_com_ldw_testjnicmake_JniUtils
#define _Included_com_ldw_testjnicmake_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ldw_testjnicmake_JniUtils
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ldw_testjnicmake_JniUtils_getJniString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
